services:
  app:
    container_name: app-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4174:4173'
    environment:
      DATABASE_URL: mysql://root:password@mysql-container:3306/database
    depends_on:
      - db
    tty: true

  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
